config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:show, :new, :create, :index]
  get "restaurants/:restaurant_id/reviews", to: "reviews#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: (0..5).to_a }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create(restaurant_params)
  end

  def update
  end

  def destroy
  end

  private

  def restaurant_params
    params.permit(:address, :name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def index
  @restaurant = Restaurant.find(params[:restaurant_id])
  @reviews = @restaurant.reviews
  end

  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_restaurant
    @restaurant = Restaurant.find([:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
</nav>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
<li>
li<%= restaurant.name %>
</li>
<li>
<%= restaurant.address %>
</li>
<li>
<%= link_to "Review", restaurant_reviews_path(restaurant[:id]) %>
</li>
<% end %>
</ul>

<%= link_to "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<%= @restaurant %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
<%= review.content %>
<% end %>
<%= link_to "Add a review", new_restaurant_review_path(:restaurant_id) %>

app/views/reviews/new.html.erb
<%= form_for(@review) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.submit %>
<% end %>